### ISSUE TITLE
package m256 does not exist

### ISSUE THREAD

**Issue by isajidh** [saccoman1974/Java-Sample-airline-booking-tool#1]
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Uncompilable source code - package m256gui does not exist
	at airlinegui.AirlineGUI.<init>(AirlineGUI.java:1096)
	at airlinegui.AirlineGUI$35.run(AirlineGUI.java:1091)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
BUILD SUCCESSFUL (total time: 4 seconds)

**Comment by saccoman1974** [comment]
hello Sajid, thanks for taking a look at my project. I have now included a m256gui jar file. please can you confirm it works? thanks.
